### ISSUE TITLE
[校对] sitmBlurbBar1 和 sitmOfferOptionBar1 

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#115]
原文1：Thank the *flashily-dressed* $manOrWoman for the drink
译文1：为对方的酒感谢那个*闪闪发光的*}$manOrWoman

原文2：A *flashily-dressed* $manOrWoman wearing a partial *salvor's rig* festooned with *shining trophies* pushes past you and buys a round for the entire bar.
译文2：一个穿着挂满*闪亮奖杯的救生装备*的{$manOrWoman}从你身边走过，为整个酒吧买了一轮酒。

此处建议进行校对

有疑问的点（非建议）
- flashily-dressed 衣着光鲜的
- salvor's rig 拾荒装备
- trophies 战利品

**Comment by TruthOriginem** [comment]
已修正
