### ISSUE TITLE
[校对] smugOfferOptionBar

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#119]
原文：Find out what the shady $smug_manOrWoman with the _off-brand_ datapad is bothering people about
译文：看看那个带着*没商标*数据平板的可疑{$smug_manOrWoman}在为了什么而问东问西

建议校对

有疑问的点（非建议）
- off-brand 杂牌，没牌子的

**Comment by TruthOriginem** [comment]
已修正
