### ISSUE TITLE
[校对/润色] CBPirate

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#120]
原文："This one's a pirate hiding out in the $bcb_systemName, that's $bcb_dist light-years away. Had a falling out with _an associate who talked_. _That gave us enough to confirm the intel._"
译文："这是个藏在{$bcb_systemName}中的海盗，距离这里{$bcb_dist}光年。对方和我们一个*爱说话的同事*吵了一架，_那给了我们足够的证据_。"

有疑问的点（非建议）
- associate who talked 也可以理解为"嘴巴被撬开的线人"
- 中文的最后半句语义不明确

**Comment by TruthOriginem** [comment]
标记为疑问
