### ISSUE TITLE
[校对] hmdfBarLookAtFreighter

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#121]
原文1：The spacer taps a few buttons on a greasy TriPad so you can see the freighter's _schematics_. 
译文1：这名船员在一块满是油污的{TriPad}上点了几下，以便你能看到这艘货船的*行程规划*。

原文2："Got a few light-years on 'er, for sure. But it'll burn bright and true," $heOrShe says _wistfully_.
译文2："应该...肯定有好几光年了。但它的引擎依旧相当健康。"{$heOrShe}*满怀希望地*说。

有疑问的点（非建议）
- schematics 设计图/构造
- wistfully 带有感伤色彩的

**Comment by TruthOriginem** [comment]
已修正
