### ISSUE TITLE
[校对] ssatOfferOptionBarUW

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#124]
原文：Join the nondescript $ssat_manOrWoman in the shadowy booth
译文：走过去，和那个{$ssat_manOrWoman}一起*站*在摊子附近

有疑问的点（非建议）
![1](https://user-images.githubusercontent.com/10858385/152988621-9d1b389a-be4d-4c8b-bcea-6ee3fe6a36ca.png)
- 从上下文来看这个人并不是站着的
- booth 有可能是指酒吧的那种小台子 (bar booth)

**Comment by TruthOriginem** [comment]
应该就是吧台
