### ISSUE TITLE
[校对] ruins_vast

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#127]
原文：$market is covered in vast ruins; cities, factories, mines, farms, homes. The dead are in dread abundance, entwined with _salvageable materials_, goods, tools, and weapons. This world is a tomb for the hubris of _the Domain's project of galactic colonization and hegemony_. 

译文：这里覆盖着巨大的废墟、城市、工厂、矿山、农场、住宅。死亡与*救助物资*、货物、工具以及武器交织在一起。此地正是}人之领}*星系殖民化和霸权项目下傲慢的坟墓*。

有疑问的点（非建议）
- salvageable materials 有利用价值的材料/物资
- 最后半句感觉需要润色

**Comment by TruthOriginem** [comment]
已解决
