### ISSUE TITLE
[润色] gaDAPirateOpenComm

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#131]
原文："This is our cache and if you know what's best you'll be burning along to find some shiny bits out elsewhere to grub at."
译文："这是我们的储藏点，如果你识相的话，你最好马上去别的有闪光碎片的地方去挖掘。"

润色的部分计划在paratranz上直接修改，此处留做记录

**Comment by TruthOriginem** [comment]
记录
