### ISSUE TITLE
[校对/润色] gaBAPirateAccept1

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#150]
原文：The comms image freezes on the pirate's diamond smile, dissipates halfway into a _hacked Tri-Tachyon holding pattern_, then blackness.
译文：通讯画面定格在海盗的钻石微笑上，消散在*黑客的{Tri-Tachyon}保持模式*中，然后是一片漆黑。

有疑问的点
- 中文语义比较模糊
- 估计是指盗用了Tri-Tach的类似“Please wait”的那种中转画面的感觉

**Comment by ck1521** [comment]
说起来Tri-Tachyon是不是未翻译词条？（速子科技）

**Comment by TruthOriginem** [comment]
已修正
