### ISSUE TITLE
[校对] gaCOPatherReject

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#152]
原文：The Pather almost smiles, like $heOrShe expected and welcomes your rejection. Here, now, $heOrShe can prove that $heOrShe is _a worthy martyr for the cause_.
译文：对方几乎笑了出来。情况正如$heOrShe所料并欢迎你的拒绝。此时此地，$heOrShe可以证明$heOrShe*是这项事业有价值的*殉道者。

有疑问的点（非建议）
- 译文的最后半句不太通顺
- worthy 称职的，合格的

**Comment by TruthOriginem** [comment]
已修正
