### ISSUE TITLE
[润色] gaCOPatherOpenComm

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#153]
原文：for you are not the first to be sent from the Galatia Academy, that foul temple of Belial which vomits up corrupt servants to broadcast profanities upon holy creation!
译文：因为你不是第一个被从Galatia学院派来的。这个Belial的肮脏圣殿，不停地吐出腐败的仆人，向神圣造物传播亵渎!

有疑问的点：
- 译文的第一个短句语序不太自然
- Belial要翻译么？

**Comment by TruthOriginem** [comment]
关于belial正在有疑问
