### ISSUE TITLE
[校对] bairdIntroScylla3

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-0951-Localization#154]
原文："Will I be blackmailing Coureuse for you?"
译文："由我来替你威逼利诱{Couresue}么？"

有疑问的点（非建议）：
- 从上下文来看，疑问的重点是Blackmailing (What doing)，而不是 I (Who)，译文的问句重点更倾向于是“我”
- 个人感觉这句话更像是“我是在替你敲诈Coureuse吗？”

相关文本（后续）：
bairdIntroScylla4a

**Comment by TruthOriginem** [comment]
已修正，仍有疑问
