### ISSUE TITLE
addPostDescriptionSection中tooltip高亮颜色指定未被尊重

### ISSUE THREAD

**Issue by Sutopia** [TruthOriginem/Starsector-0951-Localization#164]
com.fs.starfarer.api.combat.HullModEffect
addPostDescriptionSection(TooltipMakerAPI, HullSize, ShipAPI, float, boolean)方法中，調用
tooltip.addPara()
涉及核心代码，原版也不怎么用，但是Mod很多用到

**Comment by Deathfly** [comment]
推测是中文字符间插入的换行影响了高亮string的识别，正在尝试深度修复。
